name: Testing Workflows
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print gretting
        run: echo "hello world!"
      - name: Print goodbye
        run: echo "See ya later!"
  
